---
version: '3.4'
services:
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=http://localhost:9090/prometheus
      - --web.route-prefix=/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - "3001:3000"

volumes:
  prometheus:
  grafana:

